import { CheckCircle2, Clock3, History, Play, Repeat2, Trash2 } from "lucide-react";
import { calculateProgress, formatCurrency, sessionCode } from "@/lib/payment";
import type { PaymentSession } from "@/lib/types";

type Props = { sessions: PaymentSession[]; onOpen: (session: PaymentSession) => void; onRepeat: (session: PaymentSession) => void; onDelete: (id: string) => void; onClear: () => void };
export default function RecentSessions({ sessions, onOpen, onRepeat, onDelete, onClear }: Props) {
  if (!sessions.length) return null;
  return <section className="rounded-[14px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#171a20]">
    <div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold"><History size={17} />Recent sessions</h2><button type="button" onClick={onClear} className="text-xs font-semibold text-slate-500 hover:text-red-600">Clear</button></div>
    <div className="mt-3 space-y-2">{sessions.slice(0, 8).map((session) => { const progress = calculateProgress(session.payments); const complete = progress.paidCount === progress.totalCount; return <article key={session.id} className="rounded-xl border border-slate-100 p-3 dark:border-white/10"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-[11px] font-extrabold tracking-wider text-brand-600 dark:text-brand-100">{sessionCode(session.id)}</span><span className="truncate text-xs text-slate-500">{session.merchant.name}</span></div><p className="mt-1 text-lg font-bold">{formatCurrency(session.totalPaise)}</p></div><div className="text-right text-xs text-slate-500"><p>{session.payments.length} split{session.payments.length !== 1 && "s"}</p><p className={`mt-1 font-semibold ${complete ? "text-emerald-600" : ""}`}>{complete && <CheckCircle2 size={12} className="mr-1 inline" />}{progress.paidCount}/{progress.totalCount} paid</p></div></div>
      <div className="mt-2 h-1 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full bg-emerald-500" style={{ width: `${progress.percent}%` }} /></div><div className="mt-2 flex items-center justify-between"><span className="flex items-center gap-1 text-[10px] text-slate-400"><Clock3 size={11} />{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(session.createdAt))}</span><div className="flex items-center gap-1"><button type="button" onClick={() => onOpen(session)} className="flex items-center gap-1 rounded-md px-2 py-1.5 text-[11px] font-bold text-brand-600 hover:bg-brand-50 dark:text-brand-100 dark:hover:bg-brand-500/10"><Play size={12} />Resume</button><button type="button" onClick={() => onRepeat(session)} className="flex items-center gap-1 rounded-md px-2 py-1.5 text-[11px] font-bold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/5"><Repeat2 size={12} />Repeat</button><button type="button" onClick={() => onDelete(session.id)} aria-label={`Delete ${sessionCode(session.id)}`} className="rounded-md p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-500/10"><Trash2 size={14} /></button></div></div></article>; })}</div>
  </section>;
}
