import { Check, Printer, Repeat2, RotateCcw } from "lucide-react";
import { formatCurrency, sessionCode } from "@/lib/payment";
import type { PaymentSession } from "@/lib/types";

export default function SuccessScreen({ session, onNew, onRepeat }: { session: PaymentSession; onNew: () => void; onRepeat: () => void }) {
  return <section className="print-slip animate-enter overflow-hidden rounded-[14px] border border-emerald-200 bg-white text-center shadow-card dark:border-emerald-500/30 dark:bg-[#171a20]">
    <div className="bg-emerald-50 px-5 py-7 dark:bg-emerald-500/10"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-600 text-white shadow-sm"><Check size={30} strokeWidth={3} /></span><h2 className="mt-4 text-xl font-extrabold">Payment Complete</h2><p className="mt-2 text-4xl font-bold tracking-tight">{formatCurrency(session.totalPaise)}</p><p className="mt-2 text-sm text-slate-500">{session.payments.length} payment{session.payments.length !== 1 && "s"} · {sessionCode(session.id)}</p></div>
    <div className="p-5 sm:p-7"><div className="mx-auto max-w-sm divide-y divide-slate-100 rounded-xl border border-slate-100 px-4 dark:divide-white/10 dark:border-white/10">{session.payments.map((part, index) => <div className="flex items-center justify-between py-3 text-sm" key={part.id}><span className="text-slate-500">Payment {index + 1}</span><span className="flex items-center gap-2 font-bold">{formatCurrency(part.amountPaise)}<Check size={16} className="text-emerald-600" /></span></div>)}</div><p className="mt-4 text-sm font-semibold">{session.merchant.name}</p>
      <div className="no-print mt-6 grid gap-2 sm:grid-cols-3"><button onClick={onNew} className="flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-4 py-3 text-sm font-bold text-white"><RotateCcw size={16} />New payment</button><button onClick={onRepeat} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold dark:border-white/10"><Repeat2 size={16} />Repeat payment</button><button onClick={() => window.print()} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold dark:border-white/10"><Printer size={16} />Print summary</button></div></div>
  </section>;
}
